[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
